# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# sensor:
#   - platform: "eco_mane"
#     name: "EcoMane 1"
#     ip: 192.168.168.220

# sensor:
#   - platform: "eco_mane_elec"
#     name: "EcoMane ElecCheck"
#     ip: 192.168.168.220

# sensor:
#   - platform: "ecomane"
# name: "EcoMane HEMS"
# ip: 192.168.168.220

logger:
  default: info
  # logs:
  # custom_components.ecomane: debug
  # components.ecomane: info

demo:
