# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# sensor:
#   - platform: "eco_mane"
#     name: "EcoMane 1"
#     ip: 192.168.168.220

# sensor:
#   - platform: "eco_mane_elec"
#     name: "EcoMane ElecCheck"
#     ip: 192.168.168.220

# sensor:
#   - platform: "ecomane"
# name: "EcoMane HEMS"
# ip: 192.168.168.220

logger:
  default: info
  # logs:
  # custom_components.ecomane: debug
  # components.ecomane: info
  logs:
    homeassistant.components.recorder: debug
# demo:

# influxdb:
#   api_version: 2 # InfluxDB 2.xの場合
#   ssl: false
#   host: host.docker.internal
#   port: 8086
#   max_retries: 3
#   default_measurement: state
#   organization: "ivy"
#   bucket: "homeassistant"
#   token: "JjxMlfk6Chi1ZOAXvKNMk_bwLARz4qds-uUF0fxRo1yNhufdnFqnbcA-qZikBaExb-_v_wGvcf2TlCr9K7P12A==" # InfluxDB 2.xの場合

# recorder:
#   db_url: mongodb://localhost:27017/homeassistant

# recorder:
#   db_url: mysql://esphome:password@host.docker.internal/homeassistant?charset=utf8mb4
# db_url: mysql+pymysql://esphome:password@host.docker.internal/homeassistant?charset=utf8mb4
